# Generated by Django 3.2 on 2021-05-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='days',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='Monday', max_length=70),
        ),
        migrations.AddField(
            model_name='courses',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 7, 4)),
        ),
        migrations.AddField(
            model_name='courses',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 5, 9)),
        ),
        migrations.AddField(
            model_name='courses',
            name='time',
            field=models.TimeField(default=datetime.time(14, 16, 10, 257955)),
        ),
    ]
