# Generated by Django 3.1.6 on 2021-04-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='start_date',
        ),
    ]
