# Generated by Django 3.2 on 2021-05-09 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0002_auto_20210509_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.TimeField(default=datetime.time(14, 20, 55, 118868)),
        ),
    ]
