# Generated by Django 3.2.3 on 2021-05-30 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_module', '0002_alter_courses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='time',
            field=models.TimeField(default=datetime.time(17, 44, 45, 429808)),
        ),
    ]
