# Generated by Django 3.2 on 2021-04-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='D:\\Projects\\IT_APP_BOCIAN\\ITAPP_ODD_WED0730_dance_school_manager\\dance_school_manager\\media\\images'),
        ),
    ]
