# Generated by Django 3.1.5 on 2021-06-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missedcourse',
            name='is_deposit_substractred',
            field=models.BooleanField(default=False),
        ),
    ]
