# Generated by Django 3.1.5 on 2021-06-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_module', '0002_missedcourse_is_deposit_substractred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missedcourse',
            old_name='is_deposit_substractred',
            new_name='is_deposit_substracted',
        ),
    ]
